### ISSUE TITLE
Linux: Error calculating the geometry

### ISSUE THREAD

**Issue by Mx74** [stefanino-ch/lepg#2]
Hi,

I continue my investigation :-)
I simply import the demo wing, went in the geometry, checked the parameters and try to calculate the geometry. 

runPrelin.sh returns 2 errors. 
Line 9, cd $1 doesn't point on the folder where pre-1.4.out is located but on pre-1.4.out itself. Then it returns "...lepg-2_6/lepg/lep-2_60-linux/pre/pre-1.4.out: isn't a folder"

Therefore I hard replace the cd $1 by the correct folder path, and got an error at the next line:
Line 10, runPrelin.sh is looking for a file called a.out which doesn't exist in the archive.

**Comment by stefanino-ch** [comment]
Hello 
Yes please go on with all the testing. :-)
I've updated runPrelin.sh can you please download the new one and replace the one you have currently. 
Feedback is appreciated at any time.

**Comment by Mx74** [comment]
Hello I read that the tcl development is cancelled for python. 
Are you involved in this new strategy? 
Any repo for testing? 
Dev from scratch or embed in Blender, Freecad?

**Comment by stefan13131** [comment]
Hi
I‘m the one currently Wirkung on the new development, that ist true.
The repo is not yet online, as there are some final parts missing to get something meaningful out of it. 
It‘s a standalone development currently not linked to any other SW.
